version: '3.8'

services:
  server:
    build:
      context: .
    container_name: programming-languages-server
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/programmingLanguagesDB
    networks:
      - app-network

networks:
  app-network:
    external: true
